@startuml

entity "Personnage" as Pers {
  * id : int
  * nom : string
  * santé : int
  * force : int
  * agilité : int
  * position : int
  * experience : int
}

entity "Salle" as Room {
  * id : int
  * nom : string
  * description : string
  * terrain_type : string
  * locked : bool
}

entity "Objet" as Obj {
  * id : int
  * nom : string
  * type : string
  * effet : string
  * utilisable : bool
}

entity "Ennemi" as En {
  * id : int
  * nom : string
  * santé : int
  * force : int
  * agilité : int
  * salle_id : int
}

entity "PNJ" as Pnj {
  * id : int
  * nom : string
  * dialogues : string
  * salle_id : int
}
entity Quete {
  +id : u32
  +titre : String
  +description : String
  +accomplie : bool
}



' Associations
Pers -- Room : explore
Pers -- Obj : possède, utilise
Pers -- En : combat
Pers -- Pnj : parle
Pers ||--o{ Quete : suit
Room -- Obj : contient
Room -- En : héberge
Room -- Pnj : héberge

@enduml
